# This is a basic workflow that is manually triggered

name: Sysdig Runtime Context for CodeQL

on:
  workflow_dispatch:

jobs:
  start:
  # This job exists because GitHub Actions does not accept an action with dependencies in all its jobs
    runs-on: ubuntu-latest
    steps:
      - name: start
        run: echo "Starting Sysdig Runtime Insights contextualization"

  imagename:
    runs-on: ubuntu-latest
    needs: anchore-scan
    
    steps:
    - name: Print image name
      run: echo "${{ needs.anchore-scan.outputs.last-pushed-image }}""
