# This is a basic workflow that is manually triggered

name: Sysdig Runtime Insights context for CodeQL

on:
  workflow_dispatch:

jobs:
  imagename:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: anchore-scan
    
    steps:
    # Runs a single command using the runners shell
    - name: Print image name
      run: echo "${{ needs.anchore-scan.outputs.last-pushed-image }}""
