name: Sysdig Runtime Insights

on:
  workflow_dispatch:

jobs:
  sysdig-runtime-insights:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
        
    - name: Execute Sysdig Python integration
      working-directory: ./python
      run: | 
        python -m pip install requests 
        python -c 'import os;print(os.environ)'
        python test.py
      env:
        ENV_SECRET: ${{ secrets.CODESCAN_GITHUB_SECRET }} 
        REPO_SECRET: ${{ secrets.SYSDIG_SECURE_API_TOKEN }} 
