name: Sysdig Runtime Insights

on:
  workflow_dispatch:

jobs:
  sysdig-runtime-insights:
    name: Execute Sysdig Integration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8 
      env:
        ENV_SECRET: ${{ secrets.CODESCAN_GITHUB_SECRET }} 
        REPO_SECRET: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}           
      working-directory: python
      run: | 
        python -m pip install requests 
        python -c 'import os;print(os.environ)'
        python test.py
